version: '3'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    env_file: .env
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - chequeo-network

  # Uncomment this if you want to include SQL Server in your Docker setup
  # db:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourStrongPassword123!
  #     - MSSQL_PID=Express
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqldata:/var/opt/mssql
  #   networks:
  #     - chequeo-network

networks:
  chequeo-network:
    driver: bridge

# Uncomment this if you're using the SQL Server service
# volumes:
#   sqldata:
